language: python
jobs:
  include:
    - stage:
      name: "Test ML"
      python: "3.6"
      script:
        - python -m venv env
        - source env/bin/active
        - python -m pip install -r ml_reqs.txt
        - python -m pytest
    - stage:
      name: "Test frontend"
      python: "3.6"
      script:
        - python -m venv env
        - source env/bin/active
        - python -m pip install -r frontend_reqs.txt
        - python -m pytest
    - stage:
      name: "Test backend"
      python: "3.6"
      script:
        - python -m venv env
        - source env/bin/active
        - python -m pip install -r backend_reqs.txt
        - python -m pytest
